### ISSUE TITLE
Add Country as a field that can be captured?

### ISSUE THREAD

**Issue by Bas-Man** [IGI-111/torrent-name-parser#10]
Would be possible to capture country?  For shows like

Life on Mars (UK)
Life on Mars (US)

**Comment by IGI-111** [comment]
I'll have to look into how people do country codes in the wild, but that should be doable.

At the very least for UK/US overlapping content.

**Comment by Bas-Man** [comment]
This crate might be of interest in the future.

https://docs.rs/isocountry/latest/isocountry/

Provides a method to check if a two character string is a valid country code.
