### ISSUE TITLE
Shorten some Regex patterns by enabling case-insensitive option (?i)

### ISSUE THREAD

**Issue by Bas-Man** [IGI-111/torrent-name-parser#11]
Some of the regex patterns could be shortened by using the `(?i) option

```rust
    pub static ref SEASON: Pattern =
        regex!(r"(?i)s?(?P<short>\d+) ?[ex]|(season)(?:[^\d]|$)(?P<long>\d+)|s(?P<dash>\d+) - \d+");
```

I can make fork and submit a pull request if you are interested.

Really like your implementation though.

**Comment by IGI-111** [comment]
Good catch. Contribs are always welcome of course.
