### ISSUE TITLE
Season & Episode converted from string to digits

### ISSUE THREAD

**Issue by Bas-Man** [IGI-111/torrent-name-parser#15]
Question as to why season and episodes have been converted to digits?

If in the future someone, myself included, wants to build their own file name from the struct. They would need to reformat season and episode to generate the standard double digit representation.

**Comment by IGI-111** [comment]
It stems from user demands actually, people wanted to be able to do logic on the season/episode numbers. I might be willing to hear our changing that to strings, but I can't say I see a convincing case as it is.

**Comment by Bas-Man** [comment]
I guess its not that much extra work to rebuild season and episode back to strings for my purposes.
I am actually pretty far away from needing it at this stage.

**Comment by Bas-Man** [comment]
I think this is ok for me now.
