### ISSUE TITLE
Add support for file extensions (avi, mkv, mp4 and so on)

### ISSUE THREAD

**Issue by Bas-Man** [IGI-111/torrent-name-parser#16]
I tend to work with files and not directories. So I tend to use the file extension.

Add support to obtain extension.

`Doctor.Who.(2003).S01E01.avi`

**Comment by IGI-111** [comment]
The current contract is that you strip those, seemed like a reasonable demand as the user usually knows if the name being parsed is a file or a directory. It would definitely be more convenient to just throw in file names indiscriminately, but it interfered with the parser in previous versions so I'm a bit wary of that.

Definitely a good goal. But not a priority.

**Comment by Bas-Man** [comment]
I have an implementation that seems to work.

**Comment by IGI-111** [comment]
Well lemme have a look and we can get that merged in, I know it'll make some other people happy to have that.

**Comment by Bas-Man** [comment]
closed by #17
