### ISSUE TITLE
Thoughts of additional functionality for discussion

### ISSUE THREAD

**Issue by Bas-Man** [IGI-111/torrent-name-parser#18]
I have a number of other items that I would like to add. Rather than making individual issues at this time, I would like to list them here and open the discussion.

- Add is_show() method. Uses the fact that TV Shows have `Seasons` and movies do not.
- Add is_special() method. Uses the fact that TV Shows have a Season `00` for specials per TVDB database.

- Consider adding a trait for something like `short_file_name()` and or `detailed_file_name()` 
  - The idea here is developers / users could then implement their own functions to create custom file names for renaming files.
  - Of course one could also implement the `Display` trait

**Comment by IGI-111** [comment]
I like the first two.

I think the third is out of scope for this library? Though I'm not sure I understand the idea completely.

**Comment by Bas-Man** [comment]
It might be out of scope.

I am thinking of writing a library/cli for automating the organisation of files. Moving them from the download folder to the data folder, say for Plex. I have actually done this once already in Perl.
I actually thought it would be a nice project to learn more Rust. I actually going to do the file parsing before I found your nice crate :)

I was considering if I might want to clean up the file name as part of the process. But I also realise it's probably more than I need at this stage.

Regarding 1 and 2. I have working code for those. I used `is_` as I have been told it's more standard naming for boolean returns.

**Comment by IGI-111** [comment]
I knew you'd say that. You might want to have a look at https://github.com/Dusk-Labs/dim which is actually a client of this library.
I know that they have a crate for doing that kind of file parsing/renaming in their internals that's got good performance.

As for the first two I'll be happy to merge those.

**Comment by Bas-Man** [comment]
Thanks for the reference.

After the extension code is merged. I can rebase my code and submit a pull request for is_show and is_special
