### ISSUE TITLE
Episode Regex Matching Multiple Episode / use of full word `episode`

### ISSUE THREAD

**Issue by Bas-Man** [IGI-111/torrent-name-parser#20]
Hi,

Could you provide me with some examples where `episode` has been used in the naming of torrent files. I don't see any in the test cases. Perhaps reach out to any you know that use this crate?

Also, I doubt it much these days, but there were times that a single file might contain two episodes in a single file. So it would be named something like `S01E01E02`

I know this might not be an issue. But I will put it here as something to be aware of.

**Comment by IGI-111** [comment]
Here's one: `Game of Thrones Season 7 Episode 1 HDTV x264`

>there were times that a single file might contain two episodes in a single file. So it would be named something like S01E01E02

Yeah, pretty common occurrence, but I'm not sure we could support that reliably.

**Comment by Bas-Man** [comment]
Thanks for this. I will add to tests. 

I agree double episodes may be difficult. I think I handled it in a Python module I have somewhere. I will check. But it's going to be difficult to add to the api. Making devs aware of it. And how to use and check for it. Potential to create a breaking change. But I think it's avoidable. 

Might want to consider adding a change log file. And have a dev branch to merge new code to before  merging in to master.

**Comment by Bas-Man** [comment]
This is the current pattern.
[regex101](https://regex101.com/r/45MeXC/6)

This seems to work and I also have an initial working implemenation. More tests cases will be needed to ensure there is no breakage. Also need to determine naming.
