### ISSUE TITLE
Using Enums in place of some String values

### ISSUE THREAD

**Issue by Bas-Man** [IGI-111/torrent-name-parser#24]
Hi,
I was wondering if you have looked at some of the work done by @mcronce in this [optimised](https://github.com/mcronce/torrent-name-parser/tree/optimizations/src/metadata)  branch. Specifically the use of enums for the `resolution` and `quality`.

These improvements would ensure more consistent data from this crate. Allowing for more ease in generating nice output for crate users.

Thoughts?

**Comment by mcronce** [comment]
Haha I haven't had a chance to clean this up and make it PR ready yet but if there's interest I will prioritize :)

**Comment by Bas-Man** [comment]
> Haha I haven't had a chance to clean this up and make it PR ready yet but if there's interest I will prioritize :)

I am not sure if this would interest you. but you might be able to simplify this code block at the regex matching level

```rust
impl FromStr for Codec {
	type Err = Error;
	fn from_str(input: &str) -> Result<Self, Self::Err> {
		match input {
			"X264"|"x264"|"H264"|"h264"|"H.264"|"h.264" => Ok(Self::X264),
			"X265"|"x265"|"H265"|"h265"|"H.265"|"h.265" => Ok(Self::X265),
			"HEVC"|"HEVc"|"HEvC"|"HEvc"|"HeVC"|"HeVc"|"HevC"|"Hevc" => Ok(Self::X265),
			"hEVC"|"hEVc"|"hEvC"|"hEvc"|"heVC"|"heVc"|"hevC"|"hevc" => Ok(Self::X265),
			"XVID"|"XVId"|"XViD"|"XVid"|"XvID"|"XvId"|"XviD"|"Xvid" => Ok(Self::Xvid),
			"xVID"|"xVId"|"xViD"|"xVid"|"xvID"|"xvId"|"xviD"|"xvid" => Ok(Self::Xvid),
			s => Err(Error::InvalidCodec(s.into()))
		}
	}
```
replace the codec regex with
```rust
pub static ref CODEC: Pattern = 
        r"(?i)(?:(?P<x264>[xh][.]?264)|(?P<x265>[xh]\.?265)|(?P<hevc>hevc)|(?P<xvid>xvid))";
```
This regex matches all 44 string patterns you are using. Though looking at the code you would need to a function that returned a Enum::Codec instead of a str.... and bases that on a `.name("x254").or....` So might not be so useful.

Here is the link to a tool I used to test the regex [link](https://2fd.github.io/rust-regex-playground/?version=1.5.4&method=find&regex=%28%3Fi-u%29%28%3F%3A%28%3FP%3Cx264%3E%5Bxh%5D%5B.%5D%3F264%29%7C%28%3FP%3Cx265%3E%5Bxh%5D%5C.%3F265%29%7C%28%3FP%3Chevc%3Ehevc%29%7C%28%3FP%3Cxvid%3Exvid%29%29&text=X264%0Ax264%0AH264%0Ah264%0AH.264%0Ah.264%0AX265%0Ax265%0AH265%0Ah265%0AH.265%0Ah.265%0AHEVC%0AHEVc%0AHEvC%0AHEvc%0AHeVC%0AHeVc%0AHevC%0AHevc%0AhEVC%0AhEVc%0AhEvC%0AhEvc%0AheVC%0AheVc%0AhevC%0Ahevc%0AXVID%0AXVId%0AXViD%0AXVid%0AXvID%0AXvId%0AXviD%0AXvid%0AxVID%0AxVId%0AxViD%0AxVid%0AxvID%0AxvId%0AxviD%0Axvid)

**Comment by Bas-Man** [comment]
> > Haha I haven't had a chance to clean this up and make it PR ready yet but if there's interest I will prioritize :)
> 
> I am not sure if this would interest you. but you might be able to simplify this code block at the regex matching level
> 

Another option might be the regex set which allows you to test which pattern matched.
See [here](https://docs.rs/regex/latest/regex/#example-match-multiple-regular-expressions-simultaneously)

```rust
let set = RegexSet::new(&[
    r"[xh]\.264",
    r"[xh]\.265",
    ...
    ...,
]).unwrap();

// You can also test whether a particular regex matched:
let matches = set.matches("foobar");
assert!(!matches.matched(5));
assert!(matches.matched(6));
````
