### ISSUE TITLE
How to solve title name reconstruction

### ISSUE THREAD

**Issue by Bas-Man** [IGI-111/torrent-name-parser#27]
I know this is not something that the crate itself needs to handle. But I thought I would offer my thoughts here.

In a related project I am working on creating a small crate which offers some extension to this crate. I am using `traits` to extend this functionality. As part of this. I want to be able to correctly create a directory name for the torrent.

In my own planned usage of this crate I will need to correctly re-constitute the title from the `Metadata` struct.
There are some cases where this is difficult to do. This is usually due to the use of `.` periods as delimiters. Though these are also used in the final title. The cases where this happens is rather small. 

In a previous module I created using Perl I ended up using a `hash` to take deconstructed titles and provide the fixed correct title.
Example:
- `s.w.a.t.s01` gets broken down to `s w a t` but should be rebuilt as `S.W.A.T.` 
Another that I can already see having trouble is `Marvel's Agents of S.H.I.E.l.D.`
Just using the capitalise crate doesn't work as it return `S W a T`

My current idea and proto type is as follows
```rust
use std::collections::HashMap;

#[allow(dead_code)]
pub fn create_demangle_map() -> HashMap<&'static str, &'static str> {
    let title_to_fixed_title: HashMap<_, _> = [
        ("m a s h", "MASH"),
        ("s w a t", "S.W.A.T."),
        (
            "marvel\'s agents of s h i e l d",
            "Marvel\'s Agents of S.H.I.E.L.D.",
        ),
    ]
    .iter()
    .map(|&(k, v)| (k, v))
    .collect();
    title_to_fixed_title
}

#[test]
fn demangle_names() {
    let demangle_map = create_demangle_map();
    assert_eq!(demangle_map.get("test"), None);
    assert_eq!(demangle_map.get("m a s h"), Some(&"MASH"));
    assert_eq!(demangle_map.get("s w a t"), Some(&"S.W.A.T."));
    println!("{}", demangle_map.get("s w a t").unwrap());
}
```

I am building this `title-demangler` as a stand alone crate to make it easy to update without affecting `TNP`
I don't plan to make it available on `crates.io` But it might be nice to include a reference to my eventual repo so that people might contribute to it, or know how to implement it for themselves in the future.

**Comment by IGI-111** [comment]
I might actually be open to handling `A.C.R.O.N.Y.M.S.` better inside this crate since they're so common an occurrence. But not with this kind of approach, I see too many edge cases here.

However things like `M.A.S.H.` have a very recognizable `([A-Z]\.)+` format so setting up the freestanding title to include those instead of discarding them would do the trick.

At least I think that would work better than string reconstruction based on a bug.
