### ISSUE TITLE
Parse season and episode number when they are separated by `-`.

### ISSUE THREAD

**Issue by vgarleanu** [IGI-111/torrent-name-parser#5]
Some filenames containing season and episode tags separated by `-` fail to parse correctly.
```
[SubsPlease] Dr. Stone S2 - 07 (1080p) [33538C7C]
[SubsPlease] Fumetsu no Anata e S2 - 01 (1080p) [1D65E30D]
```
When these filenames are parsed the season tag gets included in the title.

**Comment by IGI-111** [comment]
Fixed as of 0.5.0
